In [1]:
from poor_man_lakehouse.polars_connector import PolarsClient, load_sql_magic

client = PolarsClient()
load_sql_magic(client)

✓ SQL magic loaded. Use %%sql to query Unity Catalog tables.
  Example:
    %%sql
    SELECT * FROM unity.default.test_table

In [3]:
print(client.show_catalog_tree())

📁 unity
  📂 default
      ├── 📄 marksheet
      ├── 📄 marksheet_uniform
      ├── 📄 numbers
      ├── 📄 test_table
      └── 📄 user_countries
  📂 demo

In [ ]:
%%sqlp
select * from unity.default.test_table

shape: (3, 2)
┌─────────┬───────┐
│ country ┆ value │
│ ---     ┆ ---   │
│ str     ┆ i64   │
╞═════════╪═══════╡
│ US      ┆ 100   │
│ CA      ┆ 200   │
│ MX      ┆ 300   │
└─────────┴───────┘

shape: (3, 2)
┌─────────┬───────┐
│ country ┆ value │
│ ---     ┆ ---   │
│ str     ┆ i64   │
╞═════════╪═══════╡
│ US      ┆ 100   │
│ CA      ┆ 200   │
│ MX      ┆ 300   │
└─────────┴───────┘